export enum UserRole {
  ADMIN = 'admin',
  USER = 'user',
  GUEST = 'guest',
  MODERATOR = 'moderator',
  SUPER_ADMIN = 'super_admin',
  EDITOR = 'editor',
  VIEWER = 'viewer',
  CONTRIBUTOR = 'contributor',
  ANALYST = 'analyst',
  SUPPORT = 'support',
  DEVELOPER = 'developer',
  TESTER = 'tester',
  MANAGER = 'manager',
  COORDINATOR = 'coordinator',
  DIRECTOR = 'director',
  EXECUTIVE = 'executive',
  INTERN = 'intern',
  FREELANCER = 'freelancer',
  PARTNER = 'partner',
  CLIENT = 'client',
  SUBSCRIBER = 'subscriber',
  MEMBER = 'member',
  ADMINISTRATOR = 'administrator',
  OWNER = 'owner',
}
